#' Subsets RVC object
#' @export
#' @name select
#' @description Produces a subset of Reef Visual Census data. 
#' @param x
#' An RVC object (generated by \code{\link{rvcData}})
#' @inheritParams rvcData
#' @param stratum 
#' A four-letter code representing the stratum
#' @param protected
#' An integer representing the protected status.
#' @param ...
#' Optional parameters passed to \code{\link{rvcData}}, e.g. server
#' @seealso \code{\link{rvcData}} \code{\link{getStat}}
#' @return Returns an RVC object with two elements:
#' \item{sample_data}{Contains the original sample data subsetted by
#' input arguments}
#' \item{stratum_data}{Contains original stratum data subsetted by
#' input arguments}
#' @examples
#' x  <- rvcData(species = c("EPI MORI", "MYC BONA"), 
#' year = 2012, region = "FLA KEYS")
#' ## Select 1 species from a group
#' select(x, species = "EPI MORI")
#' ## Select only samples from protected areas
#' select(x, protected = 1)
#' ## Select a subset of strata
#' select(x, stratum = c("FSLR","FMLR","FDLR"))
#' @note
#' All of the parameters in select can be passed to getStat. The 
#' usefullness of the select function is when a subset of the data
#' pulled off the server is used to calculate multiple statistics
select  <- function(x, species = NULL, year = NULL, region = NULL,
                    stratum = NULL, protected = NULL, ...){
  ## Parse full scientific names are trucated to SPECIES_CD
  species <- if(!is.null(species)){toSpcCd(species)};
  ## Make region/stratum codes upper case if not already
  region  <- if(!is.null(region)){toupper(region)};
  stratum  <- if(!is.null(stratum)){toupper(stratum)};
  # Throw exception if x is not an RVC object
  if (!inherits(x,"RVC")){
    stop('x must be an RVC object')
  }
  # Subset species and sample data by common values
  # Note: match function part of rvcstats package
  x  <- lapply(x, function(x){subset(x,
          YEAR %match% year &
          REGION %match% region &
          STRAT %match% stratum &
          PROT %match% protected)}
        );
  # Further subset by species 
  x$sample_data  <- subset(x$sample_data, 
                      SPECIES_CD %match% species
                           );
  # Set class to RVC
  class(x)  <- "RVC"
  return(x)
}