#' Subsets RVC object
#' @export
#' @name select
#' @description Produces a subset of Reef Visual Census data. 
#' @param x
#' An RVC object (generated by \code{\link{rvcData}})
#' @inheritParams rvcData
#' @param stratum 
#' A four-letter code representing the stratum
#' @param protected
#' An integer representing the protected status.
#' @seealso \code{\link{rvcData}} \code{\link{getStat}}
#' @return Returns an RVC object with three elements:
#' \item{sample_data}{A data frame containing the analysis ready sample data}
#' \item{stratum_data}{A data frame containing data about the stratum, including the number of 
#' possible primary sample units per stratum (NTOT)}
#' \item{lhp_data}{A data frame containing life history parameter data, including 
#' minimum length-at-capture (LC), median length-at-maturity (LM), and the allometric growth
#' parameters (WLEN_A, WLEN_B).
#'  NULL if no life history data available for selected species}
#' @examples
#' x  <- rvcData(species = c("EPI MORI", "MYC BONA"), 
#' year = 2012, region = "FLA KEYS")
#' ## Select 1 species from a group
#' select(x, species = "EPI MORI")
#' ## Select only samples from protected areas
#' select(x, protected = 1)
#' ## Select a subset of strata
#' select(x, stratum = c("FSLR","FMLR","FDLR"))
#' @note
#' \code{\link{select}} is best used to subset large amounts of data pulled off the 
#' server in \code{\link{rvcData}} into smaller manageable chunks. See
#' documentation for \code{\link{rvcData}} for more details
select  <- function(x, species = NULL, year = NULL, region = NULL,
                    stratum = NULL, protected = NULL){
  ## Parse full scientific names are trucated to SPECIES_CD
  species <- if(!is.null(species)){toSpcCd(species)};
  ## Make region/stratum codes upper case if not already
  region  <- if(!is.null(region)){toupper(region)};
  stratum  <- if(!is.null(stratum)){toupper(stratum)};
  # Throw exception if x is not an RVC object
  if (!inherits(x,"RVC")){
    stop('x must be an RVC object')
  }
  # Subset species, sample, and lhp data by provided
  # arguments
  x$sample_data  <- subset(x$sample_data,
                           YEAR %match% year &
                           REGION %match% region &
                           STRAT %match% stratum &
                           PROT %match% protected &
                           SPECIES_CD %match% species);
  if (nrow(x$sample_data) == 0){
    msg  <- paste("no rows in sample data.",
                  "make sure all fields are spelled",
                  "correctly and are available in RVC object",
                  sep = " ");
    stop(msg);
  }
  x$stratum_data  <- subset(x$stratum_data,
                            YEAR %match% year &
                            REGION %match% region &
                            STRAT %match% stratum &
                            PROT %match% protected
                            );
  if (!is.null(x$lhp_data)){
    x$lhp_data  <- subset(x$lhp,
                          SPECIES_CD %match% species);
    # If Lhp data not found, change lhp_data to NULL
    if (nrow(x$lhp_data) == 0){
      x$lhp_data = NULL;
      warning("no life history parameter data available for selected species");
    }
  }
  return(x)
}